config/routes.rb
Timecard::Application.routes.draw do
  resources :timecard
  resources :member_times
  resources :members

  root :to => 'timecard#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :created_at, :idm, :name
  validates_uniqueness_of :idm
end

app/models/member_time.rb
class MemberTime < ActiveRecord::Base
  attr_accessible :created_at, :member_id, :kind
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/member_times_controller.rb
class MemberTimesController < ApplicationController
  # GET /member_times
  # GET /member_times.json
  def index
    @member_times = MemberTime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @member_times }
    end
  end

  # GET /member_times/1
  # GET /member_times/1.json
  def show
    @member_time = MemberTime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member_time }
    end
  end

  # GET /member_times/new
  # GET /member_times/new.json
  def new
    @member_time = MemberTime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member_time }
    end
  end

  # GET /member_times/1/edit
  def edit
    @member_time = MemberTime.find(params[:id])
  end

  # POST /member_times
  # POST /member_times.json
  def create
    @member_time = MemberTime.new(params[:member_time])

    respond_to do |format|
      if @member_time.save
        format.html { redirect_to @member_time, notice: 'Member time was successfully created.' }
        format.json { render json: @member_time, status: :created, location: @member_time }
      else
        format.html { render action: "new" }
        format.json { render json: @member_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /member_times/1
  # PUT /member_times/1.json
  def update
    @member_time = MemberTime.find(params[:id])

    respond_to do |format|
      if @member_time.update_attributes(params[:member_time])
        format.html { redirect_to @member_time, notice: 'Member time was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_times/1
  # DELETE /member_times/1.json
  def destroy
    @member_time = MemberTime.find(params[:id])
    @member_time.destroy

    respond_to do |format|
      format.html { redirect_to member_times_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/timecard_controller.rb
# encoding: utf-8

require "pasori"
require "date"
require "time"

class TimecardController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def scan
    @kind = params[:kind]
    @idm = params[:idm]
    @name = params[:name]

    if @name.present?
      @member = Member.new({:idm => @idm, :name => @name})
      @member.save
    else
      @idm = scan_idm
      
      if (@idm.blank?)
        flash[:mes] = "ICカードの読み取りに失敗しました"
        redirect_to :action => "index"
        return
      end

      if (Member.exists?(:idm => @idm))
        @member = Member.find(:first, :conditions => ["idm = ?", @idm])
      else
        @member = Member.new
      end
    end

    if (@member.idm.blank?)
      respond_to do |format|
        format.html # new.html.erb
      end
    else
      member_time = MemberTime.create({:member_id => @member.id, :kind => @kind})

      name = @member.name.force_encoding('utf-8')
      @mes = ""
      @mes_sub = ""
      case @kind.to_i
      when 1
        @mes = name + " さん、おはようございます！"
      when 2
        last_member_time = MemberTime.find(:first, :conditions => ["member_id = ? AND (kind = 1 OR kind = 21)", @member.id], :order => "created_at DESC")
        if (last_member_time.present?)
          costed_time = (member_time.created_at - last_member_time.created_at).to_i
          @mes = name + " さん、お疲れ様でした！"
          @mes_sub = "勤務時間は " + (costed_time / 3600).to_s + "時間" + (costed_time % 3600 / 60).to_s + "分 です"
        else
          @mes = name + " さん、お疲れ様でした！"
        end
      when 11
        @mes = name + " さん、いってらっしゃい！"
      when 12
        last_member_time = MemberTime.find(:first, :conditions => ["member_id = ? AND kind = 11", @member.id], :order => "created_at DESC")
        if (last_member_time.present?)
          costed_time = (member_time.created_at - last_member_time.created_at).to_i
          @mes = name + " さん、おかえりなさい！"
          @mes_sub = "外出時間は " + (costed_time / 3600).to_s + "時間" + (costed_time % 3600 / 60).to_s + "分 です"
        else
          @mes = name + " さん、おかえりなさい！"
        end
      end

      @times_by_date = get_times_by_date(@member)
      @date_format = "%Y-%m-%d %H:%M:%S"
    end
  end

  def list
    @idm = scan_idm

    if (@idm.blank?)
      flash[:mes] = "ICカードの読み取りに失敗しました"
      redirect_to :action => "index"
      return
    end

    if (Member.exists?(:idm => @idm))
      @member = Member.find(:first, :conditions => ["idm = ?", @idm])
    else
      flash[:mes] = "まだ登録されていないICカードです"
      redirect_to :action => "index"
      return
    end

    @times_by_date = get_times_by_date(@member)
  end

  def list_by_id
    @id = params[:id]

    if (Member.exists?(:id => @id))
      @member = Member.find(:first, :conditions => ["id = ?", @id])
    else
      flash[:mes] = "まだ登録されていないICカードです"
      redirect_to :action => "index"
      return
    end

    @times_by_date = get_times_by_date(@member)
  end

  private
  def scan_idm
    begin
      Pasori.open {|pasori|
        felica = pasori.felica_polling(Felica::POLLING_SUICA)
        if (felica.nil?)
          felica = pasori.felica_polling(Felica::POLLING_IRUCA)
        end

        if (felica.present?)
          return felica.idm.unpack("H*").join("").force_encoding("utf-8")
        else
          return nil
        end
      }
    rescue
      return nil
    end
  end

  def get_times_by_date(member)
    nums = 14
    by_date = {}
    nums.times do |n|
      target_date = (DateTime.now - n)
      data = {}
      MemberTime.find(:all, {:conditions => ["member_id = ? AND DATE(created_at) = ?", member.id, target_date.strftime("%Y-%m-%d")], :order => "created_at DESC"}).each do |row|
        data[row.kind] = row
      end
      by_date[target_date] = data
    end
    return by_date
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_times_helper.rb
module MemberTimesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timecard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "todc-bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/member_times/_form.html.erb
<%= form_for(@member_time) do |f| %>
  <% if @member_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_time.errors.count, "error") %> prohibited this member_time from being saved:</h2>

      <ul>
      <% @member_time.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.number_field :kind %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/member_times/edit.html.erb
<h1>Editing member_time</h1>

<%= render 'form' %>

<%= link_to 'Show', @member_time %> |
<%= link_to 'Back', member_times_path %>

app/views/member_times/index.html.erb
<h1>Listing member_times</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Type</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @member_times.each do |member_time| %>
  <tr>
    <td><%= member_time.member_id %></td>
    <td><%= member_time.kind %></td>
    <td><%= member_time.created_at %></td>
    <td><%= link_to 'Show', member_time %></td>
    <td><%= link_to 'Edit', edit_member_time_path(member_time) %></td>
    <td><%= link_to 'Destroy', member_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member time', new_member_time_path %>

app/views/member_times/new.html.erb
<h1>New member_time</h1>

<%= render 'form' %>

<%= link_to 'Back', member_times_path %>

app/views/member_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @member_time.member_id %>
</p>

<p>
  <b>Type:</b>
  <%= @member_time.kind %>
</p>

<p>
  <b>Created at:</b>
  <%= @member_time.created_at %>
</p>


<%= link_to 'Edit', edit_member_time_path(@member_time) %> |
<%= link_to 'Back', member_times_path %>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idm %><br />
    <%= f.text_field :idm %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Idm</th>
    <th>Name</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.idm %></td>
    <td><%= member.name %></td>
    <td><%= member.created_at %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Idm:</b>
  <%= @member.idm %>
</p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Created at:</b>
  <%= @member.created_at %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/timecard/_form.html.erb
<%= form_tag("/timecard/scan") do |f| %>
  <%= hidden_field_tag "idm", @idm %>
  <%= hidden_field_tag "kind", @kind %>

  <div class="field">
    名前：<br />
    <%= text_field_tag "name", @name, {:style => 'width: 10em;', :maxlength => '50'} %>
    <p style="font-size: 0.5em;">idm:<%= @idm %></p>
  </div>

  <div class="actions">
    <%= submit_tag "登録" %>
  </div>
<% end %>

app/views/timecard/index.html.erb
<script>
$(function(){
  var mes = '<%= h(flash[:mes]) if flash[:mes] %>';
  var mes_sub = '<%= h(flash[:mes_sub]) if flash[:mes_sub] %>';
  var t = function(){
    var date = new Date();
    $(".time").text(date.getFullYear()  + "-" + (date.getMonth() + 1) + "-" + date.getDate() + " " + date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds());
  };

  t();
  setInterval(t, 1000);
  if (mes != '') {
    alert((mes_sub) ? mes + '\n' + mes_sub : mes);
  }
})
</script>

<h1>ICカード勤怠管理</h1>

<h2>ただいま <span class="time"></span></h2>

<h3>SuicaやPasmo（Felica準拠ICカード）をICカードリーダー（PaSoRi）の上に置いて、<br />
どれかのボタンを押して下さい。</h3>

<table>
  <tr>
    <td><%= button_to "出勤", {:action => "scan", :kind => 1} %></td>
    <td><%= button_to "退勤", {:action => "scan", :kind => 2} %></td>
  </tr>
  <tr>
    <td><%= button_to "外出", {:action => "scan", :kind => 11} %></td>
    <td><%= button_to "帰社", {:action => "scan", :kind => 12} %></td>
  </tr>
<!--
  <tr>
   <td><%= button_to "直行", {:action => "scan", :kind => 21} %></td>
   <td><%= button_to "直帰", {:action => "scan", :kind => 22} %></td>
  </tr>
-->
  <tr>
    <td colspan="2"><%= button_to "直近の勤怠状況", {:action => "list"}, {:style => "font-size: 4em; width: 100%;"} %></td>
  </tr>
</table>

<br />

app/views/timecard/scan.html.erb
<script>
$(function(){
  var t = function(){
    if (this.__counter == undefined) {
      this.__counter = 10;
    }
    $('.last_sec').text(this.__counter);
    this.__counter -= 1;
    if (this.__counter <= 0) {
      location.href = '/';
    }
  };
  t();
  var timerId = setInterval(t, 1000);

  $('.sustain').click(function(evt){
    clearInterval(timerId);
    $(evt.target).closest('h3').html('<a href="/">戻る</a>')
  });
})
</script>

<h1><%= h(@mes) %></h1>
<% if (@mes_sub.present?) %><h2><%= h(@mes_sub) %></h2><% end %>

<h3><span class="last_sec"></span> 秒後にICカード読み取り画面へ戻ります。<a href="javascript:void(0);" class="sustain">このままの画面を維持</a></h3>

<hr />

<h2>直近の勤怠状況</h2>

<%= render "shared/times" %>